export interface DataProp {
  image: string;
  user: string;
  name: string;
  ticker: string;
  marketCap: string;
  desc: string;
}

const dummyData: DataProp[] = [
  {
      image: "/cat-meme.svg",
      user: "Kokocodes",
      name: "ETH",
      ticker: "$ETH",
      marketCap: "6.74K",
      desc: "This legendary dragon is a powerful engine of destruction.",
  },
  {
      image: "/dog-meme.svg",
      user: "Bernard_01",
      name: "BTC",
      ticker: "$BTC",
      marketCap: "6.74K",
      desc: "This legendary dragon is a powerful engine of destruction.",
  },
  {
      image: "/pepe-meme.svg",
      user: "DruxAMB",
      name: "DOGE",
      ticker: "$DOGE",
      marketCap: "6.74K",
      desc: "This legendary dragon is a powerful engine of destruction.",
  },
  {
      image: "/cat.jpeg",
      user: "Charis",
      name: "ADA",
      ticker: "$ADA",
      marketCap: "6.74K",
      desc: "This legendary dragon is a powerful engine of destruction.",
  },
  {
      image: "/cat.jpeg",
      user: "Kems",
      name: "XRP",
      ticker: "$XRP",
      marketCap: "6.74K",
      desc: "This legendary dragon is a powerful engine of destruction.",
  },
  {
      image: "/man-meme.svg",
      user: "Salem",
      name: "LTC",
      ticker: "$LTC",
      marketCap: "6.74K",
      desc: "This legendary dragon is a powerful engine of destruction.",
  },
  {
      image: "/pepe-meme.svg",
      user: "Luckywemo",
      name: "DOT",
      ticker: "$DOT",
      marketCap: "6.74K",
      desc: "This legendary dragon is a powerful engine of destruction.",
  },
  {
      image: "/man-meme.svg",
      user: "Jesse",
      name: "UNI",
      ticker: "$UNI",
      marketCap: "6.74K",
      desc: "This legendary dragon is a powerful engine of destruction.",
  },
  {
      image: "/cat-meme.svg",
      user: "Alice",
      name: "SOL",
      ticker: "$SOL",
      marketCap: "5.50K",
      desc: "The sun rises and the SOL token shines brightly.",
  },
  {
      image: "/cat.jpeg",
      user: "Bob",
      name: "BNB",
      ticker: "$BNB",
      marketCap: "4.20K",
      desc: "BNB is the native cryptocurrency of Binance Chain.",
  },
  {
      image: "/pepe-meme.svg",
      user: "Charlie",
      name: "MATIC",
      ticker: "$MATIC",
      marketCap: "3.80K",
      desc: "Polygon (MATIC) is a protocol and a framework for building and connecting Ethereum-compatible blockchain networks.",
  },
  {
      image: "/cat.jpeg",
      user: "David",
      name: "AVAX",
      ticker: "$AVAX",
      marketCap: "2.90K",
      desc: "Avalanche is an open, programmable smart contracts platform for decentralized applications.",
  },
  {
      image: "/dog-meme.svg",
      user: "Eve",
      name: "ATOM",
      ticker: "$ATOM",
      marketCap: "3.30K",
      desc: "The Cosmos network and the ATOM token aim to create an Internet of Blockchains.",
  },
  {
      image: "/cat-meme.svg",
      user: "Frank",
      name: "FTM",
      ticker: "$FTM",
      marketCap: "2.60K",
      desc: "Fantom is a fast, high-throughput open-source smart contract platform for digital assets and dApps.",
  },
  {
      image: "/man-meme.svg",
      user: "Grace",
      name: "LINK",
      ticker: "$LINK",
      marketCap: "4.00K",
      desc: "Chainlink is a decentralized oracle network that provides reliable, tamper-proof inputs and outputs for complex smart contracts on any blockchain.",
  },
  {
      image: "/cat.jpeg",
      user: "Hannah",
      name: "AAVE",
      ticker: "$AAVE",
      marketCap: "2.40K",
      desc: "Aave is an open-source and non-custodial liquidity protocol for earning interest on deposits and borrowing assets.",
  },
  {
      image: "/cat-meme.svg",
      user: "Ivan",
      name: "SUSHI",
      ticker: "$SUSHI",
      marketCap: "1.20K",
      desc: "SushiSwap is a decentralized exchange and automated market maker built on the Ethereum blockchain.",
  },
  {
      image: "/dog-meme.svg",
      user: "Jane",
      name: "YFI",
      ticker: "$YFI",
      marketCap: "1.50K",
      desc: "Yearn.finance is an aggregator service for decentralized finance (DeFi) investors, using automation to allow them to maximize profits from yield farming.",
  },
  {
      image: "/pepe-meme.svg",
      user: "Ken",
      name: "ALGO",
      ticker: "$ALGO",
      marketCap: "1.70K",
      desc: "Algorand is a scalable, secure and decentralized digital currency and transactions platform.",
  },
  {
      image: "/dog-meme.svg",
      user: "Linda",
      name: "XTZ",
      ticker: "$XTZ",
      marketCap: "1.90K",
      desc: "Tezos is a new decentralized blockchain that governs itself by establishing a true digital commonwealth.",
  },
  {
      image: "/cat-meme.svg",
      user: "Favour",
      name: "XTZFGH",
      ticker: "$XTZ",
      marketCap: "1.90K",
      desc: "Tezos is a new decentralized blockchain that governs itself by establishing a true digital commonwealth.",
  },
];

export default dummyData;
