import type { Metadata } from "next";
import { Orbitron } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Ellipse from "../public/ellipse.svg";
import EllipseGreen from "../public/ellipse-green.svg";
import NavigationBar from "@/components/nav-bar";
// import OnchainProviders from "@/config/OnchainProviders";
import Footer from "@/components/footer";

const orbitron = Orbitron({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NavigationBar />
      <body className={orbitron.className}>
        <Image
          src={Ellipse}
          alt="ellipse"
          height={519}
          width={519}
          className="absolute top-2 -left-5 animate-pulse"
        />
        <Image
          src={EllipseGreen}
          alt="ellipse"
          height={519}
          width={419}
          className="absolute bottom-2 right-5 animate-pulse"
        />
        {children}
        {/* <OnchainProviders>{children}</OnchainProviders> */}
        <Footer />
      </body>
    </html>
  );
}
